language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: G/SMQH20mqAO/1e5Tl0qAMLX1PF6P5qyAzOk2SBAMpOWiLNqOMhykq5r6fiDv3WiZpKyQ3pVOm80iEgFi370xYmxPI8/cdLcWtExzdLe1aZyRFvnVvnnwe02L6aBufV1pAJhpvplZ1oam5oiC2NiiTD5aIGYpl95JPuB2d91tgcLrjg1f6NF2rH3mp4eOKLghyndfZFkD3YLKlUSczvjcJYZDpfaKjz/nOn0Eyr9EHP0j2DaO+P72adhsgvhPUZhJ4L9n/CuG6V1Krr31ApaNnKhZVkrhbp2znKcVEQXxpD6DjzjkZXZM2Us6G2NM9QUBQSv3LjZ0A/kSkccbjM8zcZHvqqXlRj5KXtUksdOIHSkZeOXsuTeBFw9+nzUiedqakCYw/WPlTUawI0UwRqtPX0BcWp0ZE2e85aB5xOBU7hgH+YGb1kwMRXkd7gfmlWj2QrUtD+nVaLLaZe7GUzr544/kQCIFmRRmBCzL4suoGlrCz+I+2CxUaVmSMRCa6rNO//T5sjwg0D5gxDx73Nm8x8ud+KQHSpkNqgEP8sYY06vJGGRiieefBhtzBjOzofyCi2oOBp7xUP0wuj1vBE9tNPuQL5vtAjHcppaHLHq2sIL/I7KavTzWyvnP/3rkr26azLfU4ShShGbW+UR5DPuELf0BQI6YHtFG57JpnLI4RQ=
  file:
    - 'html-tag-names.js'
    - 'html-tag-names.min.js'
  on:
    tags: true
